### ISSUE TITLE
error while running example

### ISSUE THREAD

**Issue by beebek** [mickey06/Flask-principal-example#1]
It generated AttributeError: 'Identity' object has no attribute 'name' while running the example.

In layout.html line no. 46, what does
                {% if g.identity.name == 'anon' %}
this "anon" means ?

**Comment by beebek** [comment]
Solved. Replacing identity.name with identity.id
Wondering dint any one tried this example. ???
Cheers...

**Comment by karl-kallavus** [comment]
@beebek same error, replacing identity.name with identity.id work great
